version: '2'
services:
  dashboard:
    image: nginx:1.11
    ports:
      - "80:80"
    volumes:
        - ./dashboard:/usr/share/nginx/html
  apiserver:
    build: api/.
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/app
  mongo:
    image: mongo:3.0
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
    driver: "local"
